import DGImage from "/assets/images/DG.jpg";
import DRRImage from "/assets/images/DRR.png";
import DRSImage from "/assets/images/DRS.jpg";

const about = {
    "District Governor": {
        content:
            "Rtn. Er. Arun Daniel Bhandare, a distinguished member of the Rotary Club of Ichalkaranji Executive, is a veteran Rotarian with over 28 years of committed service to Rotary International District 3170 and the wider community. A civil engineer by profession, he is an accomplished consultant, chartered engineer, government-approved valuer, and renowned builder known for his contribution to industrial and commercial infrastructure across the region. Raised in a joint family deeply rooted in values and culture, Rtn. Arun is known for his humility, spirituality, ethics, and commitment to social welfare. His engineering excellence has earned him accolades such as Excellence in Construction Awards (1999 & 2001), Best Engineer Award, Abhiyanta Gaurav Puraskar, and Sarvotkrushta Abhiyanta Puraskar 2024. Professionally, he is affiliated with prestigious bodies like the Indian Institute of Engineers, CREDAI, and the Indian Council of Arbitration. Beyond engineering, he has demonstrated exceptional leadership as the former President of the Builders Association of India and the Engineers & Architects Association in Ichalkaranji. Socially, he is active with the Maharashtra Chamber of Commerce, Indian Red Cross Society, and the Kolhapur Kho-Kho Association, among others. His dedication to community service earned him the Samaj Ratna National Award. In Rotary, Rtn. Arun's journey began in 1997. Over the years, he has been celebrated as Best Rotarian, Best Secretary of the District (2002-03), and Best Club President (2010-11), bagging more than 20 district awards and 4 Rotary International awards during his term. These include Significant Achievement Award, Presidential Citation with Distinction, and India National Polio Plus Award. He has served in key leadership roles like District Secretary, Assistant Governor, Conference Secretary, and District Chair Coordinator, receiving awards for each. A dedicated Major Donor to The Rotary Foundation, Rtn. Arun has also founded the Deepak Memorial Trust, investing ₹25 lakhs toward education and healthcare for underprivileged families. He is supported in his journey by his wife, Rtn. Madhavi Bhandare, a committed Rotarian and award-winning educator and Inner Wheel President. Together, they have raised three accomplished children, including an international pilot and a Go-Karting gold medalist. Rtn. Arun’s blend of professional excellence, Rotary service, community impact, and family values makes him a truly deserving and inspiring leader. His unanimous nomination as District Governor for 2025 - 26 is a testament to his dedication and vision for Rotary.",
        // image: DGImage,
    },
    "District Rotaract Respresentative": {
        content:
            "PHF DRR Rtn. Rtr. Harsh Paresh Shinde is a vibrant, passionate, and inspiring leader from Belgaum. An Architecture graduate from KLS GIT, Harsh is also a skilled digital marketer, professional anchor, and founder of his creative firm, PRAHAS, launched in 2023. His dynamic personality and versatile skill set have made him a well-known face in both professional and social circles.From a young age, Harsh displayed strong leadership abilities and a deep commitment to community service. His Rotaract journey is marked by a series of impactful roles, including President of the Rotaract Club of Venugram Belgaum (2021–22), Chief Aide to DRR, District PRO (2023–24), Zonal Representative (2024–25), and Committee Member for PR at the Rotaract South Asia Office. He currently serves as the District Rotaract Representative for 2025–26 and has also joined the Rotary Club of Venugram Belgaum.Harsh has received wide recognition for his dedication and achievements:* Best Club President of RID 3170 (2021–22)* Best International Project – Rotaract South Asia MDIO* Gold Medal for Membership Development from Past RI President Shekhar Mehta (SEARIC MDIO)* Best Rotaractor (2020–21)* Winner of the National Design Exhibition at NASA* Over 27 awards during his presidential yearHe has also been a judge, speaker, and trainer at prestigious institutions across Belgaum and beyond. Known for his extroverted nature, positivity, and dedication, Harsh continues to inspire others through his service, creativity, and deep sense of gratitude. His journey reflects a perfect blend of leadership, professionalism, and heartfelt contribution to society.",
        image: DRRImage,
    },
    "About District 3170": {
        content:
            "PHF DRR Rtn. Rtr. Harsh Paresh Shinde is a vibrant, passionate, and inspiring leader from Belgaum. An Architecture graduate from KLS GIT, Harsh is also a skilled digital marketer, professional anchor, and founder of his creative firm, PRAHAS, launched in 2023. His dynamic personality and versatile skill set have made him a well-known face in both professional and social circles.From a young age, Harsh displayed strong leadership abilities and a deep commitment to community service. His Rotaract journey is marked by a series of impactful roles, including President of the Rotaract Club of Venugram Belgaum (2021–22), Chief Aide to DRR, District PRO (2023–24), Zonal Representative (2024–25), and Committee Member for PR at the Rotaract South Asia Office. He currently serves as the District Rotaract Representative for 2025–26 and has also joined the Rotary Club of Venugram Belgaum.Harsh has received wide recognition for his dedication and achievements:* Best Club President of RID 3170 (2021–22)* Best International Project – Rotaract South Asia MDIO* Gold Medal for Membership Development from Past RI President Shekhar Mehta (SEARIC MDIO)* Best Rotaractor (2020–21)* Winner of the National Design Exhibition at NASA* Over 27 awards during his presidential yearHe has also been a judge, speaker, and trainer at prestigious institutions across Belgaum and beyond. Known for his extroverted nature, positivity, and dedication, Harsh continues to inspire others through his service, creativity, and deep sense of gratitude. His journey reflects a perfect blend of leadership, professionalism, and heartfelt contribution to society.",
        image: DRRImage,
    },
    "District Rotaract Committee Chairperson": {
        content:
            "PHF DRR Rtn. Rtr. Harsh Paresh Shinde is a vibrant, passionate, and inspiring leader from Belgaum. An Architecture graduate from KLS GIT, Harsh is also a skilled digital marketer, professional anchor, and founder of his creative firm, PRAHAS, launched in 2023. His dynamic personality and versatile skill set have made him a well-known face in both professional and social circles.From a young age, Harsh displayed strong leadership abilities and a deep commitment to community service. His Rotaract journey is marked by a series of impactful roles, including President of the Rotaract Club of Venugram Belgaum (2021–22), Chief Aide to DRR, District PRO (2023–24), Zonal Representative (2024–25), and Committee Member for PR at the Rotaract South Asia Office. He currently serves as the District Rotaract Representative for 2025–26 and has also joined the Rotary Club of Venugram Belgaum.Harsh has received wide recognition for his dedication and achievements:* Best Club President of RID 3170 (2021–22)* Best International Project – Rotaract South Asia MDIO* Gold Medal for Membership Development from Past RI President Shekhar Mehta (SEARIC MDIO)* Best Rotaractor (2020–21)* Winner of the National Design Exhibition at NASA* Over 27 awards during his presidential yearHe has also been a judge, speaker, and trainer at prestigious institutions across Belgaum and beyond. Known for his extroverted nature, positivity, and dedication, Harsh continues to inspire others through his service, creativity, and deep sense of gratitude. His journey reflects a perfect blend of leadership, professionalism, and heartfelt contribution to society.",
        image: DRRImage,
    },
    "District Rotaract Secretary": {
        content:
            "PHF DRR Rtn. Rtr. Harsh Paresh Shinde is a vibrant, passionate, and inspiring leader from Belgaum. An Architecture graduate from KLS GIT, Harsh is also a skilled digital marketer, professional anchor, and founder of his creative firm, PRAHAS, launched in 2023. His dynamic personality and versatile skill set have made him a well-known face in both professional and social circles.From a young age, Harsh displayed strong leadership abilities and a deep commitment to community service. His Rotaract journey is marked by a series of impactful roles, including President of the Rotaract Club of Venugram Belgaum (2021–22), Chief Aide to DRR, District PRO (2023–24), Zonal Representative (2024–25), and Committee Member for PR at the Rotaract South Asia Office. He currently serves as the District Rotaract Representative for 2025–26 and has also joined the Rotary Club of Venugram Belgaum.Harsh has received wide recognition for his dedication and achievements:* Best Club President of RID 3170 (2021–22)* Best International Project – Rotaract South Asia MDIO* Gold Medal for Membership Development from Past RI President Shekhar Mehta (SEARIC MDIO)* Best Rotaractor (2020–21)* Winner of the National Design Exhibition at NASA* Over 27 awards during his presidential yearHe has also been a judge, speaker, and trainer at prestigious institutions across Belgaum and beyond. Known for his extroverted nature, positivity, and dedication, Harsh continues to inspire others through his service, creativity, and deep sense of gratitude. His journey reflects a perfect blend of leadership, professionalism, and heartfelt contribution to society.",
        image: DRSImage,
    },
};

export default about;
