// councilData.js - Council Members Data

export const councilMembers = [
    // Main Leader (Top Row - 1 person)
    {
        id: 1,
        name: "Dr. Sarah Johnson",
        position: "President & CEO",
        image: "https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=400&h=400&fit=crop&crop=face",
        bio: "Leading the organization with 15+ years of experience in strategic planning and community development.",
        email: "sarah.johnson@council.org",
        phone: "+1 (555) 123-4567",
        tier: "main",
    },

    // Sub Main (2nd Row - 2 people)
    {
        id: 1,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main",
    },
    {
        id: 2,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main",
    },

    {
        id: 1,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main2",
    },
    {
        id: 2,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main2",
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        position: "Secretary General",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
        bio: "Expert in administrative affairs and organizational governance.",
        email: "emily.rodriguez@council.org",
        phone: "+1 (555) 345-6789",
        tier: "sub-main2",
    },

    {
        id: 4,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main2",
    },
    {
        id: 5,
        name: "Michael Chen",
        position: "Vice President",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
        bio: "Experienced leader in operations management and team coordination.",
        email: "michael.chen@council.org",
        phone: "+1 (555) 234-5678",
        tier: "sub-main2",
    },
    {
        id: 6,
        name: "Emily Rodriguez",
        position: "Secretary General",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
        bio: "Expert in administrative affairs and organizational governance.",
        email: "emily.rodriguez@council.org",
        phone: "+1 (555) 345-6789",
        tier: "sub-main2",
    },

    // Regular Members (3rd Row onwards - 3 per row)
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "member",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "member",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "member",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "member",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "member",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "member",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "member",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "member",
    },
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "dro",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "dro",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "dro",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "dro",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "dro",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "dro",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "dro",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "dro",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "dro",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "dro",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "dro",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "dro",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 4,
        name: "David Thompson",
        position: "Treasurer",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Financial expert with extensive background in budget management.",
        email: "david.thompson@council.org",
        phone: "+1 (555) 456-7890",
        tier: "dro",
    },
    {
        id: 5,
        name: "Lisa Park",
        position: "Head of Communications",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Communications specialist with expertise in public relations and media outreach.",
        email: "lisa.park@council.org",
        phone: "+1 (555) 567-8901",
        tier: "dro",
    },
    {
        id: 6,
        name: "Robert Kumar",
        position: "Technology Director",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
        bio: "Technology leader driving digital transformation and innovation initiatives.",
        email: "robert.kumar@council.org",
        phone: "+1 (555) 678-9012",
        tier: "dro",
    },
    {
        id: 7,
        name: "Amanda Foster",
        position: "Community Outreach Lead",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
        bio: "Passionate about community engagement and social impact programs.",
        email: "amanda.foster@council.org",
        phone: "+1 (555) 789-0123",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
    {
        id: 8,
        name: "James Wilson",
        position: "Legal Advisor",
        image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
        bio: "Legal expert specializing in organizational law and compliance matters.",
        email: "james.wilson@council.org",
        phone: "+1 (555) 890-1234",
        tier: "dro",
    },
    {
        id: 9,
        name: "Maria Gonzalez",
        position: "HR Director",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "Human resources professional focused on talent development and organizational culture.",
        email: "maria.gonzalez@council.org",
        phone: "+1 (555) 901-2345",
        tier: "dro",
    },
];

// Helper function to get members by tier
export const getMembersByTier = (tier) => {
    return councilMembers.filter((member) => member.tier === tier);
};

// Helper function to get all tiers
export const getTiers = () => {
    return ["main", "sub-main", "sub-main2", "member", "dro"];
};
